name: Create a commit on new issues
on:
  issues:
    types: [opened]

jobs:
  commit-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' |jq
        shell: bash 
          




