name: Create a commit on new issues
on:
  issues:
    types: [opened]

jobs:
  commit-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "GitHub event payload:"
          echo '${{ toJSON(github.event) }}'
        shell: bash 
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: 557858210
          body: |
            **Edit:** Some additional info
          reactions: eyes

      



