name: Create a commit on new issues
on:
  issues:
    types: [opened]

jobs:
  commit-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "GitHub event payload:"
          echo '${{ toJSON(github.event) }}'
        shell: bash 


      



